### ISSUE TITLE
Plots/outstanding

### ISSUE THREAD

**Issue by ThatGhostgirl** [Arx-Game/arxcode#106]
**Is your feature request related to a problem? Please describe.**
One command I find extremely helpful is the +firstimpressions/outstanding command, which lets me know which things I have not yet responded to. It would be very helpful to be able to do so for plots as well. Currently, I do not know of a way that indicates which plots we were invited to that we might not have accepted or addressed yet.

**Describe the solution you'd like**
add a plots/outstanding command to list the plots that need to be addressed by the character

**Describe alternatives you've considered**
Color coding or highlighting them in some way would also work.

Thanks!

**Comment by TehomCD** [comment]
Both might be a good idea from an accessibility standpoint, but I like it either way.
