### ISSUE TITLE
Staff Lore Edit

### ISSUE THREAD

**Issue by Sritterbush** [Arx-Game/arxcode#108]
**Is your feature request related to a problem? Please describe.**
Apostate was posting about some new lore updates and I was reading through when I noticed a typo, an extra word that had slipped in. When I mentioned it he said there wasn't a way to edit the lore files currently.

**Describe the solution you'd like**
A staff only edit feature for the purpose of cleaning up typos and similar when they're spotted. Preferably with versioning in case accidents happen and a file gets erased somehow.

**Comment by TehomCD** [comment]
Django admin is already a thing - he was mistaken.
