### ISSUE TITLE
Show Cost at Shop Purchase and/or Show Discounts

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#119]
**Is your feature request related to a problem? Please describe.**
Right now there's no way to see your discounts at a shop either before or after purchase. The listed shop prices always show the base price, and there's no display to show what orgs or individuals might have discounts (or markups). Finally, even when you do purchase, it doesn't tell you how much money you spent, so the _only_ way to realize you spent an amount different than the listed price is to check your inventory and see that it's not the expected amount.

**Describe the solution you'd like**
1) Have the `shop` display show the actual prices (either discounted or inflated) that would be for the character using the command. Alternatively, if that's resource-intensive, maybe at the bottom of the shop display there could be a highlighted line saying something like `You receive an additional X% off the listed price for your membership in <org>.` (Or just end it at "listed price" if it's PC-specific.)
2) Add a phrase to the shop output when you use `shop/buy` or `shop/finish` to indicate how much you spent. Right now the output for `shop/buy` is `You now have <item name> in your possession.` Maybe update to `You pay <cost> and now have <item name> in your possession.` ?

**Describe alternatives you've considered**
I thought about maybe just adding a list of org/individual cost modifiers to the bottom of the `shop` display, but I feel like showing _all_ of them might be giving out OOC information that shouldn't necessarily be accessible ICly. (Can a shop owner offer a discount to a secret org? That would be something they probably wouldn't want displayed.)

**Comment by TehomCD** [comment]
Closed in #209
