### ISSUE TITLE
Additional Flashback options

### ISSUE THREAD

**Issue by Tempest-Breakerofthings** [Arx-Game/arxcode#121]
**Is your feature request related to a problem? Please describe.**
Flashbacks are already a great tool for determining things which may have happened in the past but there are a few things I've noticed with them that could be improved.   The ability to see who has been invited to participate would be nice, as well as an indication of who opts out of participation.  Since flashbacks are not allowed to mess with current continuity, the dice roll options have been manually left off as well

**Describe the solution you'd like**
I would love to see an option where we can see the names of those we've invited,  and the ability to add in dice rolls.

**Describe alternatives you've considered**
Being clever and making a list of everyone invited first.
Having people include the roll +dicestring in the flashback pose. 

**Additional context**
This may in the future be a cool option for PRP's that have people who want to participate but due to conflicting timezone's and schedules, it may not be an option.   Obviously, these kinds of scenes can't mess with continuity, so if a PRP is done this way no one would be able to act on anything until the scene completes and a date is set.

**Comment by TehomCD** [comment]
Assigning this to NV, since we had mentioned about doing flashback enhancements. Adding dice rolls sounds great to me, even if that might be a bit tricky to implement.

**Comment by Tempest-Breakerofthings** [comment]
That's exciting! Already loving the work NV did with the outfit put and get.  

So far though the biggest drawback, I  have had with it is not being able to see who I have already sent invites to.  Even if it's not visible to the entire group.  I love that we have the web page option with them.  makes it easy to find.

**Comment by ApostateCD** [comment]
Wanted to add on to this that I've had requests for options to limit to the creator of the flashback invitation privileges, and/or the option to restrict who can see what happens earlier in flashbacks.

Flashbacks are being used more than I expected by people on limited time and offhours in order to RP, and this means many people want to RP about secrets and confidential information, and they can't do that currently if someone can oocly expose anything sensitive even by mistake. So I think we want to widen options for flashbacks in order to better accommodate players that want to have a more Play By Post forum RP style in Arx when they are on Euro time and so on.

**Comment by Tempest-Breakerofthings** [comment]
Would have a lock/unlock option work for that? Same for when the scene is 'done' so that it doesn't interfere as well as setting an ic date/timeframe when it's finished?

**Comment by Macadora** [comment]
While flashbacks are being spruced up, would it be possible to add automatic line-breaks between entries to break up the massive block of text?

**Comment by dvoraen** [comment]
I'd like to add on to this, requesting the ability to set a boolean flag on a flashback as "inform_ok" (default: true/it will `@inform` you).  And/or have the game send you a direct pemit (if you don't want an inform) that X flashback was updated by Y person.  Similarly, giving you a status update upon login that you have unchecked flashbacks, as with "you have new mail".

I've quickly discovered I'm OCD about checking informs and it easily distracts me from an actual RP scene if I get random informs, spam half my screen with the inform message, only for it to turn out to be "oh X name posted to Y flashback is all".  In other words, it feels like I'm getting informed of RP updates for a "scene" I'm "in", which is extremely redundant to someone like me, who can generally keep track of my flashbacks and doesn't want to later delete a LOT of informs.
