### ISSUE TITLE
Unable to Create New Characters/Accounts

### ISSUE THREAD

**Issue by lmclarke** [Arx-Game/arxcode#142]
**Is your feature request related to a problem? Please describe.**
When following the instructions to create a new account or character, I get an error. It's unclear what is required to fix it.

**Additional context**
> Logging in as Guest1
> You now listen to the channel Guest.  No alias added.
> 
> @add/email lala@gmail.com
> Email set to lala@gmail.com
> 
> @charcreate lala@gmail.com
> No existing incomplete character found with that email.
> Something went wrong during the character/player startup process. Please tell an admin to look into it.

**Comment by rozzingit** [comment]
You're mixing commands for two CG processes. `@add/email` is used if you're going to follow it up with `@roster/apply` to apply for a roster character. If you're starting a new original character you're building yourself, just start with `@charcreate <email>` as your first step. So maybe just try reconnecting and starting with `@charcreate` if you're going for an OC.

**Comment by lmclarke** [comment]
Thank you! I ran into this when someone else attempted to create a new account/character to log in with and look around. 

Ran through some testing. On the connection screen:

> @charcreate Tester
> Command '@charcreate Tester' is not available. Maybe you meant "@screenreader" or "screenreader"?
> 
> @charcreate Tester password
> Command '@charcreate Tester password' is not available. Maybe you meant "@screenreader" or "screenreader"?

Logged in as guest:
> @charcreate Tester
> @charcreate expects an email address to be entered with it. This allows you to resume a previous unfinished character by entering the same email address, and for your character to be approved while offline, with the password emailed to the address provided.
> 
> @charcreate Tester password
> @charcreate expects an email address to be entered with it. This allows you to resume a previous unfinished character by entering the same email address, and for your character to be approved while offline, with the password emailed to the address provided.

**Comment by rozzingit** [comment]
You have to log in as a guest and then use `@charcreate <email address>` to start a new character application. You can't create a new account/character bit until you've applied and been approved.

**Comment by lmclarke** [comment]
I'm so sorry, I'm starting to strongly suspect this is just a problem with me being dense. 

Doing the above:
> guest
> Logging in as Guest1
> You now listen to the channel Guest.  No alias added.
> 
> @charcreate test@gmail.com
> No existing incomplete character found with that email.
> Something went wrong during the character/player startup process. Please tell an admin to look into it.

**Comment by TehomCD** [comment]
I'm unable to reproduce this following the same steps you're doing. I can't find any logged traceback that would seem to originate with the guest command - are you doing this on a different server than Arx, like Ithir? If so, it's possible there might be something up on their end, and they'd have to check their logs.

**Comment by lmclarke** [comment]
I followed the directions here to install and get it running on a personal server: https://github.com/evennia/evennia/wiki/Arxcode-installing-help

It's interesting it can't be replicated - confirms it's definitely on my end, rather than in the Arx code.

**Comment by TehomCD** [comment]
The setup steps probably aren't as rigorous as they should be - likely you're missing some configuration value it's depending on. It should be printing a traceback to your terminal or server log, depending on your settings.
