### ISSUE TITLE
Propriety/View

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#15]
**Is your feature request related to a problem? Please describe.**
The propriety mods are all so cool! I want to be able to see everyone who has a certain prop mod applied to them!

**Describe the solution you'd like**
It would be AH-MA-ZING if we could see all of the people that a specific propriety mod is applied to. Like 'propriety/view Respected Artist' would spit back a list of all the PCs with that mod applied. It doesn't have to be 'propriety/view'. OBVIOUSLY. But I would absolutely love to be able to see a list, and also all of my ambiguous friends also think it's a great idea. Don't ask me for names. I don't give up names! I just ask for lists of them on command!

**Comment by TehomCD** [comment]
The command added in #77 should address this.

**Comment by Zironic** [comment]
This is now live!
