### ISSUE TITLE
the clue page has repeating clue tags

### ISSUE THREAD

**Issue by codersquid** [Arx-Game/arxcode#163]
**Is your feature request related to a problem? Please describe.**

Commit f3ac9cd1c1f2051a38bb5a82201ee700fff9af21 introduces tags to the clue page, and there are clues that show duplicate tags.

**Describe the solution you'd like**

The clue page should show a distinct list of tags.

**Describe alternatives you've considered**

Alternatively, the clue page could continue to show duplicate tags.

**Additional context**

Does anyone know the sequence of events that are followed that involve creating clue tags and attaching them to clues? If I could reproduce this I could propose some solutions.

**Comment by TehomCD** [comment]
Hmm. I think something really strange is going on with prefetch_related from testing it in shell. I'm having the prefetched objects cache be empty on a Clue object even when filtering SearchTag by the Clue id produces matches, and I think the converse of producing bogus duplicates is true also. I posted an issue about it to Evennia earlier in that SharedMemoryModel doing so much caching might be incompatible with how it works. 

I poked around the django internals for prefetching but nothing leaped out at me as being an easy solution, so I think I'll just dump the prefetch and do something else. I'll change `keywords` to be a cached property and make the query distinct for good measure.

ETA: Ah, I figured out why it'd be non-distinct. Adding filters from the querystring would cause multiple matches. It might be safe to use a `Prefetch()` with a .distinct() queryset, but I probably should avoid the implicit caching anyway.
