### ISSUE TITLE
Don't show clue list if you mistype clue number

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#164]
**Is your feature request related to a problem? Please describe.**
Right now when you use the `clue` command to look at a clue -- say `clue 1234`, if you input a number of a clue you don't actually have, it tells you: `No clue found by that ID.` Which is great! But then it also proceeds to list...your entire clue list. For some of us, that's a lot of sudden spam, and honestly you have to scroll up to even see what was wrong to begin with.

**Describe the solution you'd like**
I don't really see the utility in adding the clue list at all. Could the message be updated to something like: ``You don't have a clue with that ID. Check `clues` to see your clue list.``

**Comment by codersquid** [comment]
This bugs me too. I made a change that has the error message be the same as the error when someone calls the clue/share command  on a missing id and removed the table display. See what you think.

**Comment by TehomCD** [comment]
Resolved by #165
