### ISSUE TITLE
Show all action resources in web view

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#181]
**Is your feature request related to a problem? Please describe.**
Right now, if you check an `action` on the game, it'll show you the total number of resources invested in the action. This includes investments from any assistants as well as the leader. On the website, it _only_ shows you resources invested by the action leader. (Or by yourself, maybe?)

**Describe the solution you'd like**
Seems like it would make the most sense for the action view on the web to be the same as on the game: show the total investments in the action overall, not just what one PC has invested.

**Additional context**
I haven't checked to see if this is also the case for money and AP investments, but if it is, those should probably also show all investments made, not just from one PC.

**Comment by codersquid** [comment]
This is a simple template change, and the complicated part is the testing. if anyone has a local development environment with a database populated with characters and actions, I can walk you through changing the template.

Writing a unit test will also take a bit of work.

**Comment by codersquid** [comment]
This is the change for the template, I think.

```
diff --git a/web/character/templates/character/action_view.html b/web/character/templates/character/action_view.html
index 12e05ef..e130b41 100644
--- a/web/character/templates/character/action_view.html
+++ b/web/character/templates/character/action_view.html
@@ -40,20 +40,20 @@
             <tr>
                 <td colspan="4">
                     <br/>
-                    {% if action.silver > 0 %}
-                    <b>Silver:</b> {{ action.silver }}<br/>
+                    {% if action.total_silver > 0 %}
+                    <b>Silver:</b> {{ action.total_silver }}<br/>
                     {% endif %}
-                    {% if action.economic > 0 %}
-                    <b>Economic Resources:</b> {{ action.economic }}<br/>
+                    {% if action.total_economic > 0 %}
+                    <b>Economic Resources:</b> {{ action.total_economic }}<br/>
                     {% endif %}
-                    {% if action.military > 0 %}
-                    <b>Military Resources:</b> {{ action.military }}<br/>
+                    {% if action.total_military > 0 %}
+                    <b>Military Resources:</b> {{ action.total_military }}<br/>
                     {% endif %}
-                    {% if action.social > 0 %}
-                    <b>Social Resources:</b> {{ action.social }}<br/>
+                    {% if action.total_social > 0 %}
+                    <b>Social Resources:</b> {{ action.total_social }}<br/>
                     {% endif %}
-                    {% if action.action_points > 0 %}
-                    <b>Action Points:</b> {{ action.action_points }}<br/>
+                    {% if action.total_action_points > 0 %}
+                    <b>Action Points:</b> {{ action.total_action_points }}<br/>
                     {% endif %}
                 </td>
             </tr>
@@ -106,4 +106,4 @@
             {% endif %}
         </div>
     </div>
-{% endblock %}
\ No newline at end of file
+{% endblock %}
```

**Comment by codersquid** [comment]
If you want to show both the total and the user's contribution then it would call for a different change.

**Comment by codersquid** [comment]
The unit test did not take as much work as I expected. Cheers.

**Comment by rozzingit** [comment]
Thanks!!
