### ISSUE TITLE
AP bug in helpinvestigate swaps

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#187]
So I discovered this today (and lost an extra 10 AP in the process). Basic scenario: my PC had been helping an investigation for a couple weeks. She gets an invite to another investigation, I accidentally add her to this second investigation instead of her retainer. I get this message:

```
You use 10 action points and have 30 remaining this week.
Berenice was currently helping another investigation. Switching.
```

I realized my error, hit `helpinvestigate/stop` and got those 10 AP back, then `helpinvestigate/resume` to put her back on the first investigation...which cost me another 10 AP. Then I added her retainer to the second investigation, which also cost 10 AP. So basically: I ended up charged 20 AP for what should have been a 10 AP investment. If I had used `helpinvestigate/stop` first in the initial scenario, I would have gotten the 10 AP from the first investigation refunded, but since it _switched_ her investigation rather than stopping and starting, it charged me the AP.

So I think the bug is that if a PC switches what investigation they're helping with, it should either not charge them AP, or it should basically treat it as if you hit `helpinvestigate/stop` and refund 10 AP from dropping the first investigation and then charge it again for hopping on the second.

To make it clear, what I _should_ have done is left Berenice on the investigation she'd been helping for a couple weeks, which she already spent her initial 10 AP for some time ago, and just hopped on this new investigation with her retainer. Hence why it should have been a 10 AP cost today instead of a 20 AP cost.

**Comment by TehomCD** [comment]
should be fixed
