### ISSUE TITLE
New Petitions On Bottom

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#193]
**Is your feature request related to a problem? Please describe.**
Petitions used to be listed with new petitions on the bottom instead of the top. This matches the general pattern across the rest of the game, and I think is a good design philosophy in general for MU*s, because it avoids having to scroll up to get new information. (Which is, in turn, reverse from what's usually best for the web. But different mediums!)

Since the updates from #178 (which are awesome!!), new petitions show up at the top of the petition list. This is especially confusing because the petitions on the list from before the changeover are still in the same order. So it goes New-Old-Old-New.

**Describe the solution you'd like**
Can we have petitions sorted old to new again?

Tagging @Zironic because I believe this was his PR!

**Comment by rozzingit** [comment]
So I don't think I can reopen this myself, but -- I've realized that #198 that @codersquid did was meant to address this issue, but it looks to me like petitions are still being ordered the same way as they were before? New ones are still ending up on the top instead of the bottom.

**Comment by codersquid** [comment]
I wonder if I missed a query somewhere.

**Comment by rozzingit** [comment]
@TehomCD maybe this could be reopened until it's fixed?

**Comment by Zironic** [comment]
The place to order the query and be sure it'll work in all cases is just before this line
https://github.com/Arx-Game/arxcode/blob/d4a4c69b1b4500c3712475826b614f2b3fe072d6/world/petitions/petitions_commands.py#L143
