### ISSUE TITLE
Petition/Ignore Bug

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#194]
Since the fantabulous updates to petitions from #178 by @Zironic, there's actually a bug in the `petition/ignore` switch. That is -- it doesn't work! If you try the `petition/ignore general` or `petition/ignore <org>` options, it tells you "You are now informed..." every time so that there's no way to turn off those inform options. (If you do `petition/ignore all` it does give you feedback that it's turning the informs off.)

I SUPER appreciate having informs now, so many thanks for that. Just seems there's probably a minor bug somewhere.

**Comment by Zironic** [comment]
This bug isn't what it looks like. The ignore command itself works just fine however I completely botched the text output.

Here is a fix
 ```
   def do_ignore_switches(self):
        settings, created = self.caller.dompc.petition_settings.get_or_create()
        if self.lhs == "all":
            settings.inform ^= True
            self.msg("You are now %sinformed of new petitions." % ("" if settings.inform else "not "))
        elif self.lhs == "general":
            settings.ignore_general ^= True
            self.msg("You are now %sinformed of new general petitions." % ("" if settings.ignore_general else "not "))
        else:
            org = self.get_org_from_args(self.lhs)
            if org in settings.ignored_organizations:
                settings.ignored_organizations.remove(org)
                msg = "You are now informed of new "
            else:
                settings.ignored_organizations.add(org)
                msg = "You are now not informed of new "
            self.msg(msg + self.lhs + " petitions.")`
```

**Comment by rozzingit** [comment]
Apparently the option to ignore ALL petitions would give the right feedback, but it still wouldn't actually stop the petition informs. So idk if it's just the text output.

**Comment by Zironic** [comment]
I think I may have figured out why. 
```   
     def do_ignore_switches(self):
        settings, created = self.caller.dompc.petition_settings.get_or_create()
        if self.lhs == "all":
            settings.inform ^= True
            self.msg("You are now %sinformed of new petitions." % ("" if settings.inform else "not "))
            settings.save()
        elif self.lhs == "general":
            settings.ignore_general ^= True
            self.msg("You are now %sinformed of new general petitions." % ("" if not settings.ignore_general else "not "))
            settings.save()
        else:
            org = self.get_org_from_args(self.lhs)
            if org in settings.ignored_organizations:
                settings.ignored_organizations.remove(org)
                msg = "You are now informed of new "
            else:
                settings.ignored_organizations.add(org)
                msg = "You are now not informed of new "
            self.msg(msg + self.lhs + " petitions.")
```

**Comment by dvoraen** [comment]
I would suggest not doing XOR with True, either, unless settings.inform and settings.ignore_general are used as bitfields.  If for any reason settings.inform or settings.ignore_general are not equal to 0 or 1, the XOR with True will always return a value that evaluates to True.

See https://github.com/dvoraen/python-101/blob/master/booltest.py for an idea of what I was testing on that point.  I would suggest doing something like the below, as well as the following cosmetic change to the message to make it more clear which setting is in effect ("now" vs "not" can be easy to miss):

```Python
        settings, created = self.caller.dompc.petition_settings.get_or_create()
        if self.lhs == "all":
            settings.inform = not settings.inform
            settings.save()
            self.msg("You are %s informed of new petitions." % ("now" if settings.inform else "no longer"))
        elif self.lhs == "general":
            settings.ignore_general = not settings.ignore_general
            settings.save()
            self.msg("You are %s informed of new general petitions." % ("now" if not settings.ignore_general else "no longer"))
        else:
            org = self.get_org_from_args(self.lhs)
            if org in settings.ignored_organizations():
                settings.ignored_organizations.remove(org)
                msg = "You are no longer informed of new "
            else:
                settings.ignored_organizations.add(org)
                msg = "You are now informed of new "
            settings.save()
            self.msg(msg + self.lhs + " petitions.")
```

**Comment by Zironic** [comment]
Since they are defined as Booleans in the database model, any value other then 0 or 1 would mean you're already dealing with a bug of some sort. Also calling settings.save() in the case of the Org won't do anything because you're not updating a database row, you're creating or deleting one and Django handles those operations immediately.

**Comment by rozzingit** [comment]
Gods bless @sgsabbage.
