### ISSUE TITLE
Check a PC's Prestige

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#21]
**Is your feature request related to a problem? Please describe.**
You can use +score to see to the top 20 PCs, and +score/all to see _all_ the PCs, but you can't use +score to check just _one_ specific PC.

**Describe the solution you'd like**
It would be great to have `+score <character>` or `+score/pc <character>` or something like that -- basically some way to see the prestige scores of people outside the top 25 you get just with +score.

**Comment by TehomCD** [comment]
Also addressed in #77 I think.
