### ISSUE TITLE
Org Petitions Going to Non-Org Members

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#215]
It seems that people are sometimes getting informs for org petitions for orgs they're not members of. Some Whisper players were testing Whisper petitions tonight for one member who _wasn't_ getting informs, only to hear from someone (who, granted, was once a member of the org, but not for a good long while now) outside the org that they had seen the petition informs. So: very odd! My PC is a member of the org and also received the informs, but is not actually at an org rank that can _view_ the informs. So I'm not sure if that's an issue with the informs needing to be locked to certain ranks based on the org perm or if it's similar to the issue with people getting petition informs for orgs they're not in.

Additionally, some people who _are_ org members aren't getting petition informs for their org at all. Idk!

Tagging @emonical just cause I know the petition code is his.

**Comment by emonical** [comment]
@rozzingit: On this one, not it!

**Comment by rozzingit** [comment]
Haha jk I obviously meant @Zironic

**Comment by Zironic** [comment]
Is this still happening and do you have a reproduce-able example? Just from looking at the code I have a hard time telling where things are going awry.

**Comment by rozzingit** [comment]
It happened to me as recently as last week. I suddenly got several Society of Explorers petitions, despite not being in that org. (That alt did USED to be in that org, once upon a time a long time ago. I'm afraid I can't recall if the org petitions I've gotten erroneously have always been for orgs I used to have membership in or not.)

**Comment by Zironic** [comment]
I believe I found the bug
https://github.com/Arx-Game/arxcode/blob/d4a4c69b1b4500c3712475826b614f2b3fe072d6/world/petitions/petitions_commands.py#L233

Needs to check for deguilded. I didn't know it at the time but people stay in Orgs after they get kicked, they merely get marked as deguilded.
`.filter(owner__memberships__organization=petition.organization,owner__memberships__organization__deguilded=False)`
Might work

**Comment by rozzingit** [comment]
New thing! Yesterday I started getting an indication of new activity on an inform -- that I don't even have access to. But it's an org inform for an org my PC did used to be in.
