### ISSUE TITLE
List for +investigate/requesthelp

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#22]
**Is your feature request related to a problem? Please describe.**
The `investigate/requesthelp` command currently can only take one argument at a time. That is sad when you want to invite multiple people to an investigation!

**Describe the solution you'd like**
Can `investigate/requesthelp` instead accept a comma- or space-separated list so you can invite multiple people at once?

**Comment by Zironic** [comment]
I'll work on this today.

**Comment by Zironic** [comment]
This is now live!

**Comment by rozzingit** [comment]
Thanks!
