### ISSUE TITLE
Shop Requiring Full Price Despite Discount

### ISSUE THREAD

**Issue by Cobaltasaurus** [Arx-Game/arxcode#236]
+shop/buy is now requiring that you have the full cost of an item to let you buy it, but will still only charge you the discount price.

Example:

Josephine put a jewelry piece on her shop for a full price of 20,000, and Mirari had a discount of 15%, meaning she should pay 17,000.  With 17,050 silver in her inventory +shop/buy would not let her buy the item.  When she had 20,000 in her inventory +Shop allowed her to buy it at the 17,000 price.

**Comment by Sritterbush** [comment]
This edit should fix this problem.

`
    def pay_owner(self, price, msg):
        """Pay money to the other and send an inform of the sale"""
        loc = self.caller.location
        loc.db.shopowner.pay_money(-price)
        assets = loc.db.shopowner.player_ob.assets
        if price - price * (self.get_discount() / 100.0) >= assets.min_silver_for_inform:
            assets.inform(msg, category="shop", append=True)
`

**Comment by Sritterbush** [comment]
This check is probably caused by the if price >= assets.min_silver_for_inform check in def pay_owner. 

Proposed new code to correct this involves altering line 1124 of home.py

`        if price - price * (self.get_discount() / 100.0) >= assets.min_silver_for_inform:`

**Comment by Sritterbush** [comment]
Will test this in game after I've confirmed the game has the latest copy of the github on it, and determine if the fix worked.

**Comment by Sritterbush** [comment]
Tested, confirmed fixed.
