### ISSUE TITLE
Shop/Craft bug

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#243]
Shop/Craft passes all the craft arguments on directly to Craft which means that the list of goods added to the shop is never checked and you can shop/craft anything the crafter is capable of making regardless if they added that recipe to the shop.

The bugfix is to add a line of code to Craft that verifies that the recipe is in the shop list when the crafter isn't the caller.

**Comment by TehomCD** [comment]
Implemented by #288
