### ISSUE TITLE
Knack Crit Bug

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#257]
I am about 99% certain that the code that makes Knacks give you increased crit chance is not working. The reason is simply that the code at 
https://github.com/Arx-Game/arxcode/blob/c6340e721a112ca3cf45824f1f410061bacd3c8d/world/roll.py#L218

References "get_total_crit_chance_modifiers" but the actual function here
https://github.com/Arx-Game/arxcode/blob/424d381b04ac71c1d0dc3d7e2b86e15c27ac26f0/world/conditions/modifiers_handlers.py#L62

is named "get_crit_modifiers". The reason noone has noticed is probably because the attribute error is consumed and simply returns 0.

**Comment by TehomCD** [comment]
Good catch, thanks.

**Comment by TehomCD** [comment]
Fixed in #251, I believe.
