### ISSUE TITLE
Reset Model at Cron

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#26]
**Is your feature request related to a problem? Please describe.**
Right now modeling is run on a timer similar to actions: your modeling slots reset seven days after you use them. However, right now there's no way to actually tell when you last used them, and it can be difficult to navigate/plan out when you have enough slots to use for a whole outfit if you've used them for individual items a week ago, etc.

**Describe the solution you'd like**
It would vastly simplify things IMO if the modeling slots just reset at cron. That way people would only have to keep track of that week and they would know exactly when all their slots are free. And it would be a lot easier to manage the timing of OUTFITS if maybe one week you just had an item or two to model and the next you had a whole outfit but needed to worry about HAS IT BEEN SEVEN DAYS YET etc etc etc. Anyways this would be wonderful.

**Comment by TehomCD** [comment]
Not gonna lie, I kind of hate overloading cron. It's pretty much a bridge that's held up by toothpicks and an angry raccoon. But other people have asked for this too, so.

**Comment by rozzingit** [comment]
Poor cron. 🙁  It's currently pretty hard to keep track of modeling slots now, though. (Especially when it's got the multiple variables with overall slots vs modeling for the same org.)
