### ISSUE TITLE
Temporary lock mitigation

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#266]
Have you tried adding something like this so the database config? Supposedly the default timeout is 5 seconds which is a really long time but apparently it's not uncommon for sqlite threads to sleep for surprisingly long times.

```
DATABASES = {
    'default': {
        'OPTIONS': {
    # ...
    'timeout': 20,
    # ...
}
}
```

**Comment by TehomCD** [comment]
Yeah, I've tried different timeout values before. It made no difference that I could tell. I haven't tried recompiling sqlite with the `HAVE_USLEEP` option, but haven't really wanted to mess with that.

**Comment by Zironic** [comment]
Shouldn't USLEEP already be on by default? I think it's dubious that any kind of recompile will make a drastic difference.  What you could do is try to have Staff make a list of which commands seem to most often cause lock issues and maybe rewrite the way they call save().
