### ISSUE TITLE
Recovery (Time-Related Healing) Error

### ISSUE THREAD

**Issue by Tirost** [Arx-Game/arxcode#271]
Not sure if this should be added to the post-upgrade thread, but I received the following messaging after healing naturally due to the passing of time when the character went from minor injuries to perfect health:

Script Recovery(#None) of type 'Recovery': at_repeat() error ''NoneType' object has no attribute 'callcount''.

**Comment by rozzingit** [comment]
Looks similar to the issue with perfumes expiring, so I'll add it to the post-upgrade list.

**Comment by Tirost** [comment]
Thanks!  I'll close this one then.
