### ISSUE TITLE
Teaching Troubles! (Discussion / Proposals)

### ISSUE THREAD

**Issue by somethingfinite** [Arx-Game/arxcode#278]
**Is your feature request related to a problem? Please describe.**
I am frustrated with the way Teach currently works. I think it is a grand idea in terms of driving RP, but the execution leaves a bit to be desired. For instance - because of the nature of how skills increase the reduction, until you have fully invested in Teach, it may as well be as though you have 0 points in Teach - there are rarely bbposts asking for a teacher with a skill of 2, and it also creates a bit of a problem for those who have difficulty asking others for help, creating a very real EXP rift between those with connections and those without, and creates social pressure to invest in this skill even on characters it might not fit.

**Describe the solution you'd like**
There are a few solutions I can think of to this:

- A. Teach discounts become normalized across the board, and the only impact is how many students you can take on. (Not ideal, because it makes other ranks undesirable unless other systems are added.)
- B. Teach is removed, points are refunded, and teach caps out at a normalized exp value of 30% off, 1 slot per week. A 'teach' becomes arguably more valuable, as you must devote it to a single person.
- C. Ranks in teach influencing the speed at which a skill point is granted rather than the value of exp given. For instance, if someone is taught by someone with varying ranks, they receive their purchased skill in 4 weeks, 3 weeks, 2 weeks,. 1 week, 3 days, 1 day, instantly. Drawback would be implementing this 'delayed acquisition'.

**Describe alternatives you've considered**
Teach remains as it is, verging on 'necessary' to avoid paying increasingly high amounts of xp as tax amounts rise.

I would welcome any additional thoughts or alternatives. The current system seems like it's not quite there, yet.

**Comment by TehomCD** [comment]
C is what's been planned forever. Going to be replaced with a system where teaching reduces the time it takes to raise a skill, and xp won't be impacted at all.

**Comment by somethingfinite** [comment]
Great to hear! Thanks.
