### ISSUE TITLE
Requirements cannot be fulfilled by action assistants by default

### ISSUE THREAD

**Issue by WickedBaggins** [Arx-Game/arxcode#303]
At least in some cases, when requirements are added to an action (example: 1000 economic resources required to build King of Barns), assistants do not appear to be able to fulfill the requirements. It is possible to go into the action through django and set the assistant's status to editable.  

It would be preferable if all assistants were able to add to action requirements by default, instead of needing to be marked as editable manually. Marking the assists editable does work as a workaround, but we do have an additional problem where every field within an action requirement is marked as required (for example, django marks "Clue" as a required field for an economic resources requirement).
![requirementError](https://user-images.githubusercontent.com/66045144/83088743-c9673200-a051-11ea-940b-834eec1172c8.PNG)

**Comment by TehomCD** [comment]
Should be fixed now
