### ISSUE TITLE
@harm & Mitigation Better is Worse!

### ISSUE THREAD

**Issue by JeshinBBRP** [Arx-Game/arxcode#316]
[@harm](https://github.com/Arx-Game/arxcode/blob/b874d4c3c217df250fe3fd7ca099dc8e17386ac8/commands/cmdsets/combat.py#L1464) appears to use [attack](https://github.com/Arx-Game/arxcode/blob/e318587254fcba14f61b4fb43da993d0b43db331/typeclasses/scripts/combat/attacks.py#L324) which would also mean that the [damage](https://github.com/Arx-Game/arxcode/blob/e318587254fcba14f61b4fb43da993d0b43db331/typeclasses/scripts/combat/attacks.py#L451) is calculated using the code for attack. This means 3/4th of the damage is random. In addition [mitigation](https://github.com/Arx-Game/arxcode/blob/e318587254fcba14f61b4fb43da993d0b43db331/typeclasses/scripts/combat/attacks.py#L479) means that 1/2 of the mitigation (or armor) is random.

The downside to this is that because @harm's damage is unintuitive and not documented GMs could be pushed to larger numbers resulting in very very bad circumstances with unlucky rolls. Lets take a look...

Tehom has 100 mitigation
GM fires @harm Tehom = 100

Based on my understanding of the code that means `(armor//2) + randint(0, (armor//2))` so 100 mitigation averages out to **75!** That also means that 100 damage becomes `damage = damage//4 + randint(0, ((damage * 3)//4)+1)` so **44!** and Tehom is safe! The GM might be confused but all is well. Unless they start upping the @harm # to feel like they can get a hit and challenge high mitigation characters. Even at @harm tehom = 150 the average is 65! Against a 100 mitigation average protection of 75.

But on an improbably bad roll 100 mitigation becomes 50 and damage becomes 100 (assuming both random integers hit 0) that's 50 damage! Maximum HP for a combat PC is 120.

I think some clarification of @harm in the helpfile and/or changing harm to true damage vs mitigation would be beneficial given the rise of player GMs. The @harm/noarmor exists but it is also unsatisfying for people who have spent considerable in-game resources to not get to see their armor mitigating damage and be left to the whims of a GM on just how good steelsilk or alaricite or HQ steel really is.

edit - https://docs.google.com/spreadsheets/d/1r99afOuxfaycIj2fjjf-0OvIGoMn_nsKetNGQ-GFlz8/edit?usp=sharing I have made a google sheet to fiddle with the concept.

edit - possible alternative to this long writeup is the soak variable. Clarification would answer it!

**Comment by dreamsofgold** [comment]
To be honest, making combat code NPCs* available to PrP GMs will completely do away with the need to do that kind of adjustment AND make combat more easily resolved, when there's 8+ people participating in a plot.

* Henchmen, goons, that kind of character.

**Comment by JeshinBBRP** [comment]
I agree that permitting PrP GMs to use NPCs would be nice. However there are still circumstances such as falling rocks, a volley of arrows from a group of NPCs, a poison trap dart, running into a tree branch while fleeing from a battle, etc etc that would be beneficial for GMs to be able to use @harm. Obviously @harm/noarmor exists but as stated I think it's a let down to players who spend literal fortunes of IC resources on high end items not to get to see those items in action.

Thus understanding how the @harm command works is still beneficial for PrP GMs in the long run.

**Comment by dreamsofgold** [comment]
> I agree that permitting PrP GMs to use NPCs would be nice. However there are still circumstances such as falling rocks, a volley of arrows from a group of NPCs, a poison trap dart, running into a tree branch while fleeing from a battle, etc etc that would be beneficial for GMs to be able to use @harm. Obviously @harm/noarmor exists but as stated I think it's a let down to players who spend literal fortunes of IC resources on high end items not to get to see those items in action.
> 
> Thus understanding how the @harm command works is still beneficial for PrP GMs in the long run.

Well, they do get to see their invested silver in action through ```@harm```. I've yet to run a single scene where people who happen to have a mitigation of 80+ do not somehow shrug off over 60 points of damage. I do think documentation is more than necessary on the command , at least to get a good ballpark on the scales for damage itself. ```@harm/narmor``` suits some situations where the damage you're taking just isn't **physical** in nature, like poison, or other factors.

**Comment by TehomCD** [comment]
Will be fixed by #337
