### ISSUE TITLE
The org/briefing inform is broken

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#35]
Currently when a character is informed by org/theorybriefing they're given an inform that looks like this
**********************
XXXXX Briefing
-----------------
You've been briefed and learned a clue. Use @clue 44281 to view them:  Name of clue
You've been briefed and learned a clue. Use @clue 44282 to view them: Name of clue
You've been briefed and learned a clue. Use @clue 44283 to view them:  Name of clue
You've been briefed and learned a clue. Use @clue 44284 to view them:  Name of clue
**********************
There's one objective bug here and one request
1) It's printing the discovery ID instead of the Clue ID.
2) Since most clues are short-ish, I think it would be convenient if the clue text itself was printed into the inform.

**Comment by TehomCD** [comment]
Holdover from switching to using clue IDs rather than the discovery IDs, it looks like. And yeah, we already put clue text in other discoveries so might as well there.
