### ISSUE TITLE
Event Praise

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#39]
So Kodiak talking on MSB how he wanted to be more famous being a champion made me think it would be pretty cool if Event organizers would get a very significant pool of praise they could use to reward people who participated in the event. This could help represent things like winning a competition or being the most dazzling couple at a ball.

I would probably base it on a combination of the largesse and the prestige of the event participants and scale the effectiveness inversely with the prestige of the target. (So that less famous people have the chance to temporarily get really famous but those already famous don't get much).

**Comment by TehomCD** [comment]
How fashion was originally envisioned would be tying it directly to events, so stuff along those lines is kind of what Apostate was envisioning. Sounds worthwhile to me.

**Comment by ApostateCD** [comment]
Yeah this is stuff I want, and have talked about for a while.
