### ISSUE TITLE
Unpredictable disconnects

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#41]
Every now and then my client gets disconnected from the game, it seems to happen more on my idle clients but more rarely my active client is affected. It seems to happen after between 1 and 6 hours so I have a hard time figuring out the cause, maybe it's related to the very large input delay I sometimes experience.
 
It would be nice if it could be fixed because I like using my desktop client for logging even if I might be doing my RP from my laptop.

**Comment by rozzingit** [comment]
This might be an issue with your personal connection. What client are you using, and what does your "NOPKEEPALIVE" on @option say?

**Comment by Zironic** [comment]
Client settings (telnet):
+---------------+------------+
| Name          | Value      |
+~~~~~~~~~~~~~~~+~~~~~~~~~~~~+
| ANSI          | True       |
| CLIENTNAME    | MUSHCLIENT |
| ENCODING      | utf-8      |
| FORCEDENDLINE | True       |
| INPUTDEBUG    | False      |
| MCCP          | True       |
| MXP           | True       |
| NOCOLOR       | False      |
| NOGOAHEAD     | True       |
| NOPKEEPALIVE  | True       |
| OOB           | False      |
| RAW           | False      |
| SCREENHEIGHT  | 45         |
| SCREENREADER  | False      |
| SCREENWIDTH   | 102        |
| TERM          | mushclient |
| XTERM256      | True       |
+---------------+------------+

I'll change it to False and see how it goes however if that's the issue, maybe that option should be set by default?

**Comment by TehomCD** [comment]
I want to say that the reason it's typically off is to prevent visible characters from popping up on some clients, depending on how they interpret it. We already deal with that sort of thing due to MXP though, so might be worth changing it.

**Comment by rozzingit** [comment]
Sometimes doing a client-side timer can help with this too, since it's often a matter of someone's personal connection on their end. `none` will work in a client timer to basically ping the game without getting any output back. I think if you do a client-side timer you want to keep NOKEEPALIVE to True, but you could also try making that False without exploring a client timer and seeing if that helps!

**Comment by Zironic** [comment]
I've been running a 60 minute timer that does TIME. In most games I do @@ which is equivalent to none.

**Comment by Zironic** [comment]
So I've been trying
option NOPKEEPALIVE=False

And it seems to work. However it also resets to True each time I connect a client, which is very annoying.

**Comment by rozzingit** [comment]
Oh I know how to fix that! Do @option/save and it'll stick.

**Comment by emonical** [comment]
@TehomCD: Close with 'invalid'?

**Comment by Zironic** [comment]
Is there any reason for @option to not save by default?

**Comment by TehomCD** [comment]
No clue! It's a stock Evennia command, so you'd need to ask Griatch that. He'd probably accept a PR to change the default behavior if there's no compelling reason to keep it that way. Anyhoo, glad setting `NOPKEEPALIVE` resolves it.
