### ISSUE TITLE
Clout, Power Curve and the Average Case

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#43]
Reading the MSB thread there appears to be a re-occuring frustration from players that praises and modeling from non-specialised characters have almost no effect and from Staff that people very rarely use modeling. 
 
I think that has much to do with the extreme curve that these systems are using where the low end is actually 2-3 order of magnitude smaller then the high end and looking at the comment in the fashion code, that seems to have been done on purpose.
 
I think that if you want to encourage these systems to be more widely used, you need to make the results produced by an average character using it in an intended way much closer to the high end results and that will require tightening of clout benefits across the board. 
 
Right now if you take say a character with Composure 4, Performance 3 and Clout 5, which if you'd believe the helpfiles is a pretty social character and run them through the fashion roll. They'll come out with 132 on average while a 5/5/10 character runs 430 and 5/5/20 averages 811and 5/5/30 1265. Meanwhile a non-social character will get squashed by the 30 difficulty and come out with a 1.
 
If for instance, all characters no matter how terrible they were would be guaranteed a result of 100 here +/- some fuzzing, then all characters would be getting some decent fame for showing up in new snazzy stuff even if only 1/8th of the higher end socialites.
  
In the land of praise because your praise is basically Clout*Prestige mod, a low end character might have 5 clout and 50 prestige modifier for a total of 250 while someone with 20 clout and 100 prestige have 2000 before accounting for the charm+propaganda roll itself. I think similarly here you could just give people who are below 5 clout/50 prestige a push up to that level which would atleast let them praise in the 5000 range instead of 10.

I know I started this talking about the average and ended up talking about the low end, but that's what happens when you write these things at 3am. The suggestions are arbitrary to illustrate the idea.

**Comment by Zironic** [comment]
Related to this. The current version of the audience code for modeling scales linearly with the amount of people in the room and their social ranks up to the cap of 7. I think that somewhat discourages 'casual' modeling since the difference in returns between modeling an outfit at a 'small' social event with 3 princesses and a marquiss and the assembly of peers can be sevenfold. It also somewhat discourages people who live outside the US since Arx events almost always run at 21:00 EST which is 03:00 Central European Time which is not a sensible time to be awake just because you want to come across as fashionable.

My proposal would be to make the audience calculation logarithmic.  Assuming log2, a single princess would net you a 3, a small party would be about 4.6 and the assembly of peers would be about 9.

**Comment by ApostateCD** [comment]
I actually -don't- want praise to be more widely used, for the simple fact that if it was a global, easily accessible system everyone would use, then 'message the entire player base=please praise me' would be the normal. Right now people know it's social characters that are impactful so they go to them, and not as a global resource of everyone.

On the other hand, I would be very okay with changing the org sponsorship mechanic to be way more powerful, so those useless praises are situationally way more powerful because of it and have utility there. Since that's essentially a team work mechanic.

**Comment by Zironic** [comment]
If that's your intent with praise then the current formula should work just fine. I do still think low-end modeling should be better though.

By org sponsorship, do you mean favor/disfavor or the sponsoring org for modeling?

Also I made this sheet to calculate the optimal fame level for any given character using the current prestige gains, the only sad thing is that for both of my characters it always says 0 :p 
https://docs.google.com/spreadsheets/d/1CUCXlY9TU59YG7hwSm6-E4L8M8Y-nX0pUTL2nOAC-qU/edit?usp=sharing

The only thing it doesn't account for is that you can get better then silver*3 in outfit fashion value through haggling and recipe values.

**Comment by ApostateCD** [comment]
No, it's a little known thing for events where if an org sponsors an event, people can use praises to praise that org at the event for a huge base increase to praises. So normally worthless praises aren't worthless. Problem is it's too clunky, as people are disinclined to both do that and save their praises for that kind of niche case.
