### ISSUE TITLE
The Roll code does not keep bonus keeps

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#45]
In the work code, a dice check is called with the org mod as bonus dice and org mod // 2 as bonus keep. However as far as I can determine, once that enters the roller itself it's completely discarded.

        keep_dice = DEFAULT_KEEP + self.bonus_keep
        if self.stat_keep:
            keep_dice += statval
        if self.skill_keep:
            if len(self.stats) == 1 and statval:
                keep_dice = 1 + (statval // 2)    <<<< Overwrites bonus keep
           keep_dice += skillval

**Comment by TehomCD** [comment]
Oh, good catch! I thought org rolls seemed a little low...
