### ISSUE TITLE
XP Cost consistency

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#46]
The way the XP tax is currently calculated, you're actually charged a different amount of tax based on the order you buy your skills with it as a rule of thumb being cheaper to buy expensive things as early as possible.
 
This could be prevented entirely by changing the way XP tax is calculated to take the new rating into account. Since the cost increase function is linear the end result will always be:
costincrease = (get_skill_cost_increase()*2+cost * 0.02)/2
 
That would mean trying to buy a 1000xp legendary raw in chargen would end up costing 2000 because of incremental tax.

**Comment by TehomCD** [comment]
Yeah, it sounds reasonable to me to add the cost of the thing itself to the tax value.

**Comment by rozzingit** [comment]
> That would mean trying to buy a 1000xp legendary raw in chargen would end up costing 2000 because of incremental tax.

Am I getting this right: there would be no way to buy a legendary skill at less that 2000 xp?

**Comment by Zironic** [comment]
Yes, that's because 1000xp by itself generates 200% tax and would thus get taxed at 100%.

**Comment by rozzingit** [comment]
😬

**Comment by rozzingit** [comment]
Sorry I will leave actual thoughts, which: I do understand the logic of this for sheet building in general, but I think it's particularly rough to apply it to a legendary in that way to basically entirely double the base cost.

**Comment by Zironic** [comment]
I think there's a lot that can be said on the subject of legendariers and their cost. Between this proposed change and them now fully generating XP tax, they are I believe almost impossible to buy for any reasonable character.  There's this ticket by Durendington that's a good place to discuss it https://github.com/Arx-Game/arxcode/issues/48

I think this way of handling XP tax is objectively better because it now won't matter in which order you buy anything, buying X dots will always cost Y XP (before accounting for training) and that fixing the XP tax merely illustrates that Legendary prices may have been very high.

**Comment by rozzingit** [comment]
I think the general 1000 xp cost has been fairly decent just in terms of -- it's been attainable but _with effort_. It shouldn't be an easily accessible thing, no, but it also shouldn't be impossible. If @TehomCD goes for a linear tax like this, which I can see the fairness of, it might be worth considering halving skills at 6 to 500 so that their "base cost" as it would show up would start at 1000. (Or whatever would tax up to 1000, it might be between 500 and 1000.) Which would also lessen the big tax jump that just happened at least a little bit?

**Comment by TehomCD** [comment]
Legendary costs being very high doesn't bother me much, but being raised higher than it was before does - I don't want newer players to feel at a pronounced disadvantage. My feeling is that lowering the base to 500 is probably a good compromise.

**Comment by Zironic** [comment]
At 500 base, the starting price for a non-combat legendary would be 750 and a combat legendary would be 2000.
 A character with 50 dots purchased would be looking at a non-combat legendary price of 1250 and a combat legendary price of 3000.

I think for non-combat legendariers that looks very reasonable compared to how they worked before.
