### ISSUE TITLE
Minor thing with the xp patch

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#49]
The base cost passed into the xp-tax function needs to be divided by 2 if you want the xp tax to be fully consistent. You can check that easily by seeing that the integral for x/50 for any given values of X are going to be (x(2)-x(1)) * (x(2)-x(1))/2+x(1))/50

https://www.wolframalpha.com/input/?i=integrate+x%2F50+from+x%3D15+to+x%3D100

(100-15) * ( (100-15)/2+15)/50 =97.75

**Comment by TehomCD** [comment]
I apologize, but I don't really follow this. `get_skill_cost_increase` sums `cost_per_rank` for each of their existing skills, then applies modifiers from xp bonuses in character creation. Why would adding the `cost_per_rank` of the new skill rank bought introduce an inconsistency?

**Comment by Zironic** [comment]
Hmmm, actually you might be right. It'll work just fine this way too.

500*(1000/500)+50*(1050/500)=1105
50*(550/500)+500*(1050/500)=1105
