### ISSUE TITLE
The code to investigate a clue appears to have a syntax error

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#52]
Repeat the command to confirm and continue.
You use 100 action points and have 114 remaining this week.
You spend 0 social resources to start a new investigation.
AttributeError: 'Clue' object has no attribute 'tags'
An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
(Traceback was logged 2018-12-04 03:42:26-0500).

I believe the issue is here on line 196 of web/character/investigation.py
`                search_tags = list(source_clue.tags.all())`

Clues don't have tags, they have search_tags

**Comment by TehomCD** [comment]
Dang it. That appears to be a regression, I remember fixing that.
