### ISSUE TITLE
Legendary Discount Edge Case

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#55]
If anyone tries to buy a legendary while they still have a discount, they'll get it relatively cheap since they'll be buying it for the cost in dots (50) until they run out of dots and then only remaining dots will be taxed.

In the long term it'll hardly matter(even in the short term they probably only save 100xp or something, although considering how training works it can end up saving them upwards of 450xp), since they'll still be fully taxed on all future spends but it's a curiosity of the implementation. I would probably suggest blocking legendaries until all discounts are spent even though that will prevent my characters dream of snatching a legendary for 725 xp <.<

**Comment by TehomCD** [comment]
NV had the same concerns, and I think it does probably diminish their prestige a bit to be bought with catchup xp.
