### ISSUE TITLE
@check/retainer

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#63]
**Is your feature request related to a problem? Please describe.**
Retainers have stats and skills, which is cool! But there's currently no way to do a `@check` with their stuff other than `@gmcheck`, where you have to put the numbers in manually. Which is both a hassle and, well, people can kind of say their retainer stats are -- whatever they want to say they are. So you don't have the same sort of assurances.

**Describe the solution you'd like**
`@check/retainer`! I'm thinking of the syntax `@check/retainer <retainer ID#>/<stat>[+<skill>][ at <difficulty number>][=receivers]`. So as close as possible to the original `@check` syntax, just with that retainer ID thrown in first. The idea of course being to do a dice roll of the given retainer stat+skill and display it like a PC:

`<DICESTRING> RETAINER NAME checked dexterity + athletics at difficulty 15, rolling 52 higher.`

**Comment by Zironic** [comment]
This sounds sensible and easy enough to implement to me. While we're at it, I'd suggest all retainer commands should be updated to accept retainer references by name.
