### ISSUE TITLE
Broker Buy Orders

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#66]
Currently the way the broker works is that you can only place items up for sale and if you want to buy, you need to buy them by ID, which is a bit convoluted and involves copy pasting.

I think the broker experience for both buyers and sellers would be improved if you coded buy orders.  They would work like this.

1) When you place a buy order at the price X, then you're immediately charged X*amount which goes into a market deposit, then the code will automatically buy all sell orders cheaper then X until you run out amount. If two sell orders have the same price, the oldest one is bought first, any remaining amount is placed on the market as a standing buy order. If you cancel a buy order you're refunded any remaining deposit.
2) When you place a sell order at price X, then the code will automatically fill any buy orders above X and the remaining amount is placed on the market as a sell order.

This way.
A) Noone ever has to manually type order IDs.
B) Merchanile types can put up very large standing buy orders instead of spending hours sitting at the city center.
C) Most sellers should have a much easier time liquidating their writs.

**Comment by TehomCD** [comment]
Yeah, this is something Apostate's wanted for a while. I probably won't get to it any time soon, but it's a good idea.

**Comment by Zironic** [comment]
I could probably write you the code for it if you want to, it should be reasonably uncomplicated.

**Comment by TehomCD** [comment]
Oh sure! I'd happily accept PRs for it. I'd just ask that you include tests for it, though that should be reasonably straightforward. Adding to the existing broker test would be great.

**Comment by Zironic** [comment]
This should work, I make no promises because I was really tired when I wrote it.
https://github.com/Zironic/arxcode/commit/6683324bd7db0fe84d7a971bc24fd58a70ad67be

I can do it more properly on Saturday complete with tests, probably.

**Comment by TehomCD** [comment]
I think I'd like to wait for tests, but no rush on it or anything - initial pass looked good, though I think you might need to define the `SALE` and `PURCHASE` constants for the choices tuple unless they were defined elsewhere that I've forgotten about. You might have to make a migration for the field you added so that Travis doesn't fail with an OperationalError, but not positive on that.

**Comment by Zironic** [comment]
It almost certainly needs a migration or all the broker commands will fail.
To do list:

- [x] Define constants
- [x] Fix syntax error for constants
- [x] Remove the duplicate pay money in make purchase
- [ ] Migration
- [ ] Reword the messages to be more appropriate.
- [ ] Write tests

**Comment by Zironic** [comment]
So while I make the neat version of this, is there any particular reason that the broker code is inside the petitions file?

**Comment by TehomCD** [comment]
I wanted an app that'd represent offers made by players to one another. So it's petitions, deals, contracts, etc.

**Comment by Zironic** [comment]
Would you mind if I throw all the message strings into a class variables so that all 50 or so tests don't have to be redone by hand when the wording is changed?

Todo:
Make sure buyer/seller is properly paid/refunded when catching a cheaper/more expensive order
Make sure orders looped through are price sorted
Double check you can't sneak in a negative number anywhere.
Make sales and purchases printed to a log for debugging and usage tracking.

**Comment by TehomCD** [comment]
Yeah, it'd be fine to make all the messages into class variables.

**Comment by TehomCD** [comment]
And this should be live now thanks to #73 . Thanks much!
