### ISSUE TITLE
Revising +Buildroom Helpfile

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#83]
The +buildroom helpfile currently just has a barebones syntax that works with the code but not with the standard Arx formatting. A number of people go through +buildroom and don't realize that the "Housing and Shops Guide" helpfile, which has way more detail, exists. With that in mind, could we just add a second paragraph to the helpfile at the end that reads like this (or similarly):

`For information about proper colors, formatting, naming, and exit conventions, see also "help housing and shops guide".`

**Comment by TehomCD** [comment]
I kind of hate hard-coding a reference to a database entry. I wonder if we could use tags to associate expanded help to commands, and do a quick search for associated entries or something.

**Comment by rozzingit** [comment]
I think it would be _super_ useful to build in a system of helpfile associations so that those suggestions could be more useful. In the meantime though, I will say that I've talked to a fair number of folks who end up missing that guide altogether because they just end up at the buildroom helpfile, so I'd still say it'd be nice to reference it now. (Also I think it was @Packetdancer that totally put in hard references to other helpfiles in the duel helpfile so you should blame her.)

**Comment by TehomCD** [comment]
Making a note for plot/goals to also link to 'help plot guide' and the other guide files.
