### ISSUE TITLE
Discussion: Relative effectiveness of the various paths to fame

### ISSUE THREAD

**Issue by Zironic** [Arx-Game/arxcode#91]
The fame systems are a bit special in that they all involve you investing silver or resources and getting Fame back. This means that it's relatively easy to compare how much fame you get from each system for any given investment.

Now Donate and Invest distinguish themselves from Modeling and Largesse in that they grant you more then just fame, specifically Reputation and Work Mod development.

Let's take a character with 5's in all relevant stats and 20 clout to compare these four systems.

When you donate, then you make a roll at difficulty 10, then your roll is divided by 100 and multiplied by the value /2. This means most of the time our testing character will get 1/3rd of their donation back in fame.

(57+20-10) /100 / 2 = 0.335

When you make an investment, you earn 
((clout * 5) + 50) * org_amount in fame
That means our testing character earns 150 fame per resource and since the default value of resources is 250, it means investing gets you about  150/250 = 0.6 fame per silver.

Sidenote: Minimum invests are a lot more efficient but more complicated to compare since we need to start putting silver values on AP

With the audience multiplier removed, the expected fashion result for our testing character using Umbra is 
(MAX(POW(MAX(57-30+3*20,1),1.5),1)*7*5/40000)
Which is 0.7 fame per outfit value.  With Umbra the silver to outfit value is about 5 (16k to make for 90k outfit value) for a total of 3.5 fame per silver.

With the new Largesse values, you're looking at 20 fame per silver at the low end of 'grand events' to 8 fame per silver for extravagant.

In terms of tiers, I think this looks pretty good. Events are better then fashion which is better then donate/work however Donate is truly like a red-headed stepchild here since it's quite a bit worse then work/invest yet reputation does basically nothing right now while work/invest upgrades your entire org. One solution would be to make is 2-5 times stronger, a better one would be to do something interesting with reputation. 

Another thing worth exploring is that since you've implemented fame categories now, you could implement different decay rates for different kinds of fame. So you can have some fames which are explosive and vanish quickly and some fames which build slowly over time and take a long time to fully go away. Things like donations and work/invest could go into that latter category where the decay rate could be something like 0.1.

**Comment by TehomCD** [comment]
I think my preference, speaking only for myself, would be to make reputation more meaningful, and have donate distinguished that way. I feel that otherwise, donate doesn't have much reason to exist compared to work/invest.

The fame records are only used for calculating titles rather than their current prestige values afaik so having separate decay rates might be messy since it wouldn't be reflected in their actual prestige values. It's not a bad idea from a standpoint of intuitive feel, but I think the complexity cost in implementation might just be too high.

**Comment by Zironic** [comment]
You'd basically just have to make separate pools for each different rate of decay you want to support. It would become complex if you wanted to support a lot of different rates, or track how much prestige still lingers from any particular event in the past (since then you'd need to keep a record for each fame event) but just two or three rates would be relatively simple I think since you'd just store it as 2-3 different values that are then merged into 'fame' the same way prestige is the merge of fame+grandeur+legend+propriety.

**Comment by Packetdancer** [comment]
Speaking for myself, I really feel fairly strongly that the redesigned system needs to be as straightforward as possible: you do things and you gain fame and/or legend.  Fame decays, legend doesn't.  Period.  If we make it overly complex with different _types_ of fame, not just different sources, then I think people are going to feel overwhelmed in engaging with it, which is not the goal; frankly, we're already complex enough, inasmuch as we have fame, legend, grandeur, propriety, and we still need to work in reputation. 

(Further, I suspect if there were different decay rates people would lose their minds about 'optimizing' prestige gains.)

**Comment by Zironic** [comment]
I don't think players need to be directly exposed to the complexities of fame behind the scenes just like they're not directly exposed to how all the calculations work right now. The average player isn't overly concerned about optimizing prestige gains, as evidenced by the non-zero amount of people using donate even though it's fairly obvious it's many times worse then all the other fame options right now, they mostly just want to do what makes sense for their character to do.

However if you do want to keep the fame system simple and straight forward, I'd suggest standardizing the fame equations so the various fame options are a lot more closer in magnitude then they are now. For instance they could all use the same basic equation (with different stats/skills used) with some sort of multiplier to determine general effectiveness.
